### ISSUE TITLE
ValueError: [E002] Can't find factory for 'textdescriptives' for language English (en).

### ISSUE THREAD

**Issue by id8314** [HLasse/TextDescriptives#10]
## How to reproduce the behaviour
import spacy
import textdescriptives as td
nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("textdescriptives") 
doc = nlp("The world is changed. I feel it in the water. I feel it in the earth. I smell it in the air. Much that once was is lost, for none now live who remember it.")
doc._.readability
doc._.token_length

## Environment
Name: textdescriptives Version: 0.1.1
Windows 10
Python 3.6

## Error message

ValueError: [E002] Can't find factory for 'textdescriptives' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, parser, beam_parser, entity_linker, ner, beam_ner, entity_ruler, lemmatizer, tagger, morphologizer, senter, sentencizer, textcat, spancat, textcat_multilabel, en.lemmatizer
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-6a8f1264f269> in <module>
      6 import textdescriptives as td
      7 nlp = spacy.load('en_core_web_sm')
----> 8 nlp.add_pipe('textdescriptives')
      9 doc = nlp('This is a short test text')
     10 doc._.readability # access some of the values

~\.conda\envs\tdstanza\lib\site-packages\spacy\language.py in add_pipe(self, factory_name, name, before, after, first, last, source, config, raw_config, validate)
    780                 config=config,
    781                 raw_config=raw_config,
--> 782                 validate=validate,
    783             )
    784         pipe_index = self._get_pipe_index(before, after, first, last)

~\.conda\envs\tdstanza\lib\site-packages\spacy\language.py in create_pipe(self, factory_name, name, config, raw_config, validate)
    639                 lang_code=self.lang,
    640             )
--> 641             raise ValueError(err)
    642         pipe_meta = self.get_factory_meta(factory_name)
    643         config = config or {}

**Comment by HLasse** [comment]
Hi! Thanks for posting the issue. It seems you're using a very old version of textdescriptives (0.1.1) which uses stanza and not spacy as the backend. The current version is 1.0.4 - please try updating, that should fix the issue. Let me know if it doesn't

**Comment by id8314** [comment]
Thank you. I'll get back as soon as I can try it. I'm behind a corporate firewall and numpy>=1.20.0 is not available yet...

**Comment by HLasse** [comment]
@id8314 I've changed the required numpy version to numpy>=1.15.0. Does this fix it for you?
