### ISSUE TITLE
Enable horizontal scrolling in tutorial notebooks

### ISSUE THREAD

**Issue by HLasse** [HLasse/TextDescriptives#124]
Can't spot the difference with timeseriesflattener. 
Perhaps @MartinBernstorff can help when he gets back?

**Comment by KennethEnevoldsen** [comment]
Martin does not have a solution to this except scaling down the tables. That is naturally an option we can use if we want.

**Comment by HLasse** [comment]
Unfortunately, I think that scaling/subsetting would remove the main purpose of the tables (showing how many/which metrics are extracted). I vote keep as is - looks a bit off on the website, but notebooks look great and I don't think the problem is large enough that it warrants that much extra time

**Comment by KennethEnevoldsen** [comment]
Agree. We should probably create an issue on furo though to let them now of the problem.
