### ISSUE TITLE
Add Arxiv link to readme

### ISSUE THREAD

**Issue by impredicative** [HLasse/TextDescriptives#141]
Perhaps the following link to the corresponding Arxiv article can be included in the readme:

https://arxiv.org/abs/2301.02057

**Comment by KennethEnevoldsen** [comment]
Thanks @impredicative we should def. do that. @HLasse we should also the `citation.cff` for integrations with e.g. zotero. The citation cff can also included references to [preprint](https://github.com/KennethEnevoldsen/tomsup/blob/master/citation.cff) and papers.

**Comment by HLasse** [comment]
Thanks both! I'm on it

**Comment by KennethEnevoldsen** [comment]
@HLasse I already created a PR #142

**Comment by HLasse** [comment]
MVP 🙌
