### ISSUE TITLE
Add_pipe problem

### ISSUE THREAD

**Issue by ray4wit** [HLasse/TextDescriptives#15]
Hello,
I am tying textdescriptives on a Python 3.6 + spaCy3.1 on a Linux system through JupyterLab. 

I found this error. Not quite sure how to deal with spaCy decorator. Could you please help?  Thanks!

nlp.add_pipe("textdescriptives") 

ValueError: [E002] Can't find factory for 'textdescriptives' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

**Comment by HLasse** [comment]
Hi, thanks for posting the issue. What version of textdescriptives are you running?

**Comment by ray4wit** [comment]
Hello HLasse,

I used 1.0.3 to avoid the 1.20+ numpy requirement in 1.0.2 and 1.0.1.

Thanks,

**Comment by HLasse** [comment]
Try updating to 1.0.4 - the numpy requirement has been downgraded to 1.15+

**Comment by ray4wit** [comment]
My apology... I was using 1.0.4 rather than earlier version.
