### ISSUE TITLE
How is `doc_length` different from other length measures such as `n_characters`?

### ISSUE THREAD

**Issue by sudarshan85** [HLasse/TextDescriptives#168]
Hi,

I realize this is a question and not a bug report. But when I tried to open the discussions forum I got a DNS error. Thus, I'm posting the question here.

As the title says, how is `doc_length` measured? We have other length measures such as `n_characters` , `n_sentences` etc which are self-explanatory in terms of how they are measured. However, I'm not clear what `doc_length` is actually measuring.

**Comment by KennethEnevoldsen** [comment]
doc_length is `len(doc)`, I.e. the number of tokens. However, it is not the same as `n_tokens` (from descriptive stats) as 
it filters punctuations and similar non-word tokens. Hopefully this answer your question.

@HLasse we should probably make `n_tokens` --> `n_words` and make a `n_tokens` in descriptive stats as well which is equal to `len(doc)`. In the quality component, we should rename the `doc_length` to `n_tokens`. Do you agree with this?

**Comment by sudarshan85** [comment]
Thank you for your reply.

> doc_length is len(doc), I.e. the number of tokens. 

Is this the lengh of SpaCy tokens? 

> However, it is not the same as n_tokens (from descriptive stats) as it filters punctuations and similar non-word tokens.

Could you please tell which one does what? Does `n_tokens` filer puncts?

**Comment by KennethEnevoldsen** [comment]
Yes n_tokens filters puncts, while doc_length doesn't filter anything.
