### ISSUE TITLE
Pyphen does not support all languages that spaCy does

### ISSUE THREAD

**Issue by HLasse** [HLasse/TextDescriptives#218]
## How to reproduce the behaviour
For instance, Pyphen does not support Finnish. We should either 1) raise an error if people try to extract metrics requiring pyphen from an unsupported language, 2) print a warning and return np.nan for the related metrics.

**Comment by KennethEnevoldsen** [comment]
Warning and nan are probably more stable, but I think the error lead to fewer errors.

Another option is to warn and then remove it as a feature? (so that it wouldn't get a column in the dataset?)
