### ISSUE TITLE
Listed metrics deviate between extraction functions in docs

### ISSUE THREAD

**Issue by LudvigOlsen** [HLasse/TextDescriptives#219]
The listed available metrics in the docstrings for the extract_* functions differ even though they should be the same. Seems these docstrings could use an update :-)

**Comment by HLasse** [comment]
Perhaps we should refer to the [`textdescriptives.utils.get_valid_metrics`](https://github.com/HLasse/TextDescriptives/blob/7da3c8e65314bb76e1523dbcef147200e9dd443a/src/textdescriptives/utils.py#L11) function?

**Comment by LudvigOlsen** [comment]
You mean it's better to automate updating this than going through it manually every now and then when someone makes an issue? 

Do you know how to generate parts of docstrings dynamically? I haven't tried that before.

**Comment by KennethEnevoldsen** [comment]
I think lasse means that we can update the [docs](https://hlasse.github.io/TextDescriptives/extractors.html#api) from:

```
Which metrics to extract. One or more of [“descriptive_stats”, “readability”, “dependency_distance”, “pos_proportions”, “coherence”, “quality”]. If None, will extract all metrics from textdescriptives. Defaults to None.
```

to:
```
Which metrics to extract. Could for example include one or more of [“descriptive_stats”, “readability”, “dependency_distance”, “pos_proportions”, “coherence”, “quality”]. To see the full list available metrics see `td.get_valid_metrics()`. If None, will extract all metrics from textdescriptives. Defaults to None.
```

**Comment by KennethEnevoldsen** [comment]
The metrics are already all available in the get_valid_metrics and will be updated automatically when new components are added as the use the `registries` from spacy.

**Comment by LudvigOlsen** [comment]
How often do you add metrics? Shouldn't it be possible to manually update it? Search for one of the metrics in the repo and add it everywhere. But yes, having it as an extra (in case docs aren't updated, look here) thing, seems fine. Autogenerating that part of the docstring (if possible) also seems fine though.

**Comment by KennethEnevoldsen** [comment]
It would be (but you could quite often miss a few places. This allows for mistakes while still allowing the user to figure out what the valid metrics are (It also allows user to add their own metrics).


> Which metrics to extract. Could for example include one or more of [“descriptive_stats”, “readability”, “dependency_distance”, “pos_proportions”, “coherence”, “quality”]. To see the full list available metrics see `td.get_valid_metrics()`. If None, will extract all metrics from textdescriptives. Defaults to None.

**Comment by KennethEnevoldsen** [comment]
But we should def. just update the docstring to be the same.
