### ISSUE TITLE
References for readability metrics

### ISSUE THREAD

**Issue by ogencoglu** [HLasse/TextDescriptives#232]
What are the sources for the current readability metrics listed in [docs](https://hlasse.github.io/TextDescriptives/readability.html)? Why were they chosen and are there any papers that introduce or compare them?

**Comment by KennethEnevoldsen** [comment]
Hi @ogencoglu. What would you like to know? Formula, scientific references? Then I will make sure to  update the documentation (which is admittedly lacking at the moment).

I believe it was @HLasse whom implemented it originally as [spacy readability](https://github.com/mholtzscher/spacy_readability) package did not allow for  spacy 3.

**Comment by KennethEnevoldsen** [comment]
I have made a PR #233 Which specifically address this. Hopefully it includes the information you are looking for @ogencoglu.

**Comment by ogencoglu** [comment]
Thanks a lot! Appreciated!

**Comment by HLasse** [comment]
Hi there! The readability metrics are largely derived from the implementation of the [textstat](https://github.com/textstat/textstat) package. The specific metrics were chosen because they are language agnostic and do not require a list of e.g. hard words. 

Thanks for the PR, @KennethEnevoldsen!
