### ISSUE TITLE
Update quality filters to be pydantic v.2.0 compliant / convert to dataclasses

### ISSUE THREAD

**Issue by HLasse** [HLasse/TextDescriptives#324]
Spacy <3.6.0 seems to require pydantic <2.0 (see image). So, tradeoff here. Do we want to support multiple spacy versions by requiring pydantic to be <2.0, OR do we require a newer version of spacy to be able to support newer versions of pydantic.

Alternatively, we can rewrite to `dataclass`, but then we lose this [amazing documentation](https://hlasse.github.io/TextDescriptives/quality.html#textdescriptives.components.quality_data_classes.QualityThresholds) from [autodoc_pydantic](https://autodoc-pydantic.readthedocs.io/en/stable/index.html).  (although I don't know how well [sphinx's autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) handles dataclasses with metadata fields.

<img width="794" alt="image" src="https://github.com/HLasse/TextDescriptives/assets/23191638/716f5165-f469-43a0-87b7-17c5596a71f3">

**Comment by HLasse** [comment]
@KennethEnevoldsen any thoughts on this?

**Comment by KennethEnevoldsen** [comment]
Seems like spacy is working on pydantic v2, I either go with keeping the pydantic version in line with spacy or convert it to a dataclass. We don't really gain a lot from using a pydantic object here I believe a dataclass could do just fine as well.
