### ISSUE TITLE
All text statistics of information_theory are NaN due to the failure to download the lexeme probability table

### ISSUE THREAD

**Issue by zhenfoxz** [HLasse/TextDescriptives#359]
Hi:
<img width="706" alt="image" src="https://github.com/user-attachments/assets/b7c9bbfa-3a79-4272-81a9-38689f31a1bc">

I came across this bug: 
All text statistics of information_theory are NaN due to the failure to download the lexeme probability table. Could you please help? Thank you so much!

**Comment by KennethEnevoldsen** [comment]
Hi @zhenfoxz as seen in the warning this is expected behaviour. Given that the lexeme probability table is unavailable.

Surprised that it is unavailable for English though you might need to load the lookup table: 

https://github.com/explosion/spaCy/discussions/6388#discussioncomment-330606

@HLasse should we add this to the warning?

**Comment by zhenfoxz** [comment]
> Hi @zhenfoxz as seen in the warning this is expected behaviour. Given that the lexeme probability table is unavailable.
> 
> Surprised that it is unavailable for English though you might need to load the lookup table:
> 
> [explosion/spaCy#6388 (comment)](https://github.com/explosion/spaCy/discussions/6388#discussioncomment-330606)
> 
> @HLasse should we add this to the warning?

Thank you for the reply. I tried to add these lines of code:
```
lookups = load_lookups("en", ["lexeme_prob"])
nlp.vocab.lookups.add_table("lexeme_prob", lookups.get_table("lexeme_prob"))
```
but then I receive this error message:
<img width="863" alt="image" src="https://github.com/user-attachments/assets/3f79f13e-2db9-4c9c-bdf0-19a72105650f">

May I ask for more help? Thank you so much!

**Comment by HLasse** [comment]
Definitely seems like a bug - I'll have a look this week

**Comment by zhenfoxz** [comment]
Thank you a lot!

**Comment by HLasse** [comment]
@zhenfoxz what version of spaCy are you using?

**Comment by zhenfoxz** [comment]
It's 3.7.1

**Comment by HLasse** [comment]
@zhenfoxz can you try updating spaCy to the newest version (3.7.6)? The following works fine for me there

```python
import spacy
import textdescriptives as td
nlp = spacy.load("en_core_web_lg")

nlp.add_pipe('textdescriptives/information_theory')

doc = nlp("This is a simple text")
doc._.perplexity
doc._.entropy
td.extract_df(doc)
```

**Comment by HLasse** [comment]
Closing this for now. Please re-open if you still encounter the issue, @zhenfoxz
