### ISSUE TITLE
Support for Danish (perplexity and entropy)  ???

### ISSUE THREAD

**Issue by javaberlin** [HLasse/TextDescriptives#369]
### Discussed in https://github.com/HLasse/TextDescriptives/discussions/368

<div type='discussions-op-text'>

<sup>Originally posted by **javaberlin** December 13, 2024</sup>
Hi,

I am trying to use textdescriptives with  Dacy and a Danish language model to calculate perplexity and entropy,  but  I get the error :

```
⚠ Could not load lexeme probability table for language da. This will
result in NaN values for perplexity and entropy.
```
```python
nlp = dacy.load("large")
nlp.add_pipe("textdescriptives/dependency_distance")
nlp.add_pipe("textdescriptives/readability")
nlp.add_pipe("textdescriptives/information_theory")
```

Is that another way to make the library work with Danish when calculating entropy and perplexity ?

Thank you</div>

**Comment by KennethEnevoldsen** [comment]
Answered in discussion. As noted this is outside of textdescriptives so will close this issue, but hopefully the linked PR in the discussion should be merged and we can have a fix for this.
