### ISSUE TITLE
Formulae for dependency distance calculation on Doc level

### ISSUE THREAD

**Issue by bma-vandijk** [HLasse/TextDescriptives#77]
Hi,

first of all thanks for this very helpful library. I have a question regarding the way dependency distance (DD) for Doc objects is calculated. 

Your function on calculating DD for a Doc, returns the DD value here: `"dependency_distance_mean": np.mean(dep_dists)`. The mean returned is as far as I can see, the mean over mean DD of every sentence (contained in `dep_dist`) constituting the Doc object. 

the two sources you cite on dependency distance in your documentation ([Liu 2008](https://pdfs.semanticscholar.org/b6b9/cf00698a76d7a1e5ba58baa92d8799366813.pdf) and [Oya, 2008](http://www.paaljapan.org/conference2011/ProcNewest2011/pdf/poster/P-13.pdf)), however, have a different approach. 

For calculating DD of a text, Liu seems to take the sum of the absolute DD found in the whole text and multiplies by (1 / (number of words - the number of sentences). Oya seems to takes a mean of means like you do, but for a sentence averages sum of absolute DD over the number of dependency links in an utterance. In your documentation nor in your code I can retrieve how you exactly calculate DD for a text.

Would you please be so kind as to explain with what approach you calculate DD for Doc objects, and provide pointers on how we may adapt the code to e.g. implement approaches by Liu and Oya? Thanks!

## Which page or section is this issue related to?
https://hlasse.github.io/TextDescriptives/dependencydistance.html

**Comment by HLasse** [comment]
Hi @bma-vandijk, thanks for the question and for using the library!
The logic for calculating DD is contained in [`textdescriptives/components/dependency_distance.py`](https://github.com/HLasse/TextDescriptives/blob/master/textdescriptives/components/dependency_distance.py) with the main logic happening in [`token_dependency`](https://github.com/HLasse/TextDescriptives/blob/master/textdescriptives/components/dependency_distance.py#L32).

The implementation in textdescriptives follows Oya - we calculate the distances from each token to their dependent, and take the mean of this for calculation the mean dependency distance for spans. In our implementation, we calculate the Doc level DD by averaging over the sentence-level mean DDs.

To get the sentence level means as in Oya, you could simply do
```py
dep_dists, adj_deps = zip(
            *[sent._.dependency_distance.values() for sent in doc.sents]
        )
```
To calculate the metric you cite from Liu (sum(DD) * (1 / (number of words - the number of sentences))
you could so something like the following (assuming you have added the dependency distance pipeline)
```py
def liu_doc_dependency(doc: Doc) -> float:
    """Calculate mean dependency distance from Liu, 2008"""
    # get sum of token level dependency distance
    dd = sum[token._.dependency_distance["dependency_distance"] for token in doc]
    return dd * (1 / (len(doc) - len(list(doc.sents))))
```
Let me know if you have any other questions!

**Comment by KennethEnevoldsen** [comment]
@HLasse let us add this to the documentation as well

**Comment by bma-vandijk** [comment]
This is super late, but I would still like to thank you for your swift and helpful response :)
