### ISSUE TITLE
Write JOSS paper

### ISSUE THREAD

**Issue by HLasse** [HLasse/TextDescriptives#80]
- [ ]  Summary describing the purpose of the software
- [ ]  Statement of need
- [ ]  Package features & functionality
- [ ]  Target audience
- [ ]  References to other software addressing related needs
- [ ]  Past or ongoing research projects using the software

**Comment by KennethEnevoldsen** [comment]
Google docs or just markdown?

**Comment by HLasse** [comment]
Ready for review

**Comment by KennethEnevoldsen** [comment]
review done, ready for feedback

**Comment by KennethEnevoldsen** [comment]
Submitted 🥂
