### ISSUE TITLE
Separate component loaders

### ISSUE THREAD

**Issue by HLasse** [HLasse/TextDescriptives#85]
We should consider separating some of the components from each other, so the user doesn't get overloaded.  (also, speed)

I propose:
1. `textdescriptives`: includes everything but `quality``
2. `quality`: only quality

Thoughts, @KennethEnevoldsen ?

**Comment by KennethEnevoldsen** [comment]
Hmm, maybe it is better to have simple groups like:

This would encourage people to only add what they need while still having meaningful categories.
```
# {the package}.{the thing you add}
nlp.add_pipe("textdescriptives.quality")
# could potentially even split it in two
nlp.add_pipe("textdescriptives.repetition")

nlp.add_pipe("textdescriptives.descriptive_stats") 
nlp.add_pipe("textdescriptives.readability") 
nlp.add_pipe("textdescriptives.text_complexity") # dependency distance
nlp.add_pipe("textdescriptives.pos_stats")
```


should be quite easy to do with the existing codebase.

**Comment by KennethEnevoldsen** [comment]
This would also make it quite easy to structure the documentation.
